version: "3.9"
services:
  api:
    image: tvoordeel
    restart: unless-stopped
    ports:
      - "3000:8080"
    entrypoint: ['yarn', '--cwd', './packages/api', 'run', 'start']
  landingspagina:
    image: tvoordeel
    restart: unless-stopped
    ports:
      - "3001:3000"
    entrypoint: ['yarn', '--cwd', './packages/landingspaginas', 'run', 'start']
    environment:
      - NODE_ENV=production