version: "3.9"
services:
  api:
    image: tvoordeel
    restart: unless-stopped
    ports:
      - "${API_PORT}:8080"
    entrypoint: ['yarn', '--cwd', './packages/api', 'run', 'start']
  landingspagina:
    image: tvoordeel
    restart: unless-stopped
    ports:
      - "${LANDINGSPAGINA_PORT}:3000"
    entrypoint: ['yarn', '--cwd', './packages/landingspaginas', 'run', 'start']
    environment:
      - NODE_ENV=production